<a href="https://colab.research.google.com/github/VishwakarmaMithun/PythonScripts/blob/main/Python_Numpy_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr  =np.arange(0,11)

In [6]:
arr[8]
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [5]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
slice_of_arr  = arr[0:5]

In [8]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [9]:
slice_of_arr[:]=99

In [10]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [11]:
arr_copy = arr.copy()

In [12]:
arr_copy[:]=100

In [13]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [17]:
arr_2d = np.array([[5,10,15],[20,25,40],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 40],
       [35, 40, 45]])

In [18]:
arr_2d.shape

(3, 3)

In [19]:
arr_2d[0,2]

15

In [21]:
 arr_2d[:2,1:]

array([[10, 15],
       [25, 40]])

In [22]:
arr = np.arange(1,11)

In [23]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr >4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [25]:
bool_arr = arr >4

In [26]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [27]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [28]:
import numpy as np

In [29]:
arr  = np.arange(0,10)

In [30]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr +  5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
arr -2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [33]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
arr -arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr /arr

<ipython-input-36-47932f420b68>:1: RuntimeWarning: invalid value encountered in divide
  arr /arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])